name: menu_zen_restaurant
description: "A restaurant menu app that allows users to view and order food items."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  auto_route: ^10.1.0+1
  retrofit: ^4.6.0
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  skeletonizer: ^2.1.0+1
  equatable: ^2.0.7
  logger: ^2.6.1
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_photon: ^2.0.1
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  flavor_getter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  injectable_generator: ^2.7.0
  build_runner: ^2.5.4
  retrofit_generator: ^9.7.0
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  assets:
     - .env.local
     - .env.staging
     - assets/images/.
     - assets/icons/.

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
