name: menu_zen_monorepo
publish_to: none

environment:
  sdk: ^3.10.0

dev_dependencies:
  melos: ^7.5.1

workspace:
  - apps/menu_zen_tablet
  - apps/menu_zen_mobile
  - packages/domain
  - packages/data
  - packages/design_system

melos:
  sdkPath: auto
  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: Analyze all packages
    format:
      run: melos exec -- dart format .
      description: Format all packages
    build_runner:
      run: melos exec --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
      description: Run code generation in packages that use build_runner
    clean:
      run: melos exec -- flutter clean
      description: Clean all packages
    get:
      run: melos exec -- flutter pub get
      description: Get dependencies for all packages
